# Server configurations
server:
 port: 6980
 ginMode: "debug"
 verbose: true

database:
 uri: "mongodb://192.168.1.117:27017"
 db: "home"

station-rest-client:
 baseURL:        "http://"
 connectTimeout: 50
 timeout:       100
 disableCache:   true
 disableTimeout: false

slow-station-rest-client:
 baseURL:        "http://"
 connectTimeout: 100
 timeout:       200
 disableCache:   true
 disableTimeout: false

mqtt:
  minInterval: 30s
  stationCommandTopic: "command/%s"
  pingTimeOut: 2s
  keepAlive: 120s
  userName: dispatcher
  clientId: iot-dispatcher-dev

cron:
  #desabilitado revisar comentario en cron.go, se me recargaba antes que ejecute alguna tarea
  reloadTaskSpec: "@every 0h10m5s"